# tests/test_tools/test_github_tool.py
import pytest
from unittest.mock import MagicMock, AsyncMock, patch
from app.tools.github_tool import GithubTool


@pytest.mark.asyncio
async def test_create_repo_returns_full_name():
    """PyGithub create_repo path --- no MCP server."""
    tool = GithubTool()
    mock_repo = MagicMock()
    mock_repo.full_name = "testorg/my-app"
    mock_user = MagicMock()
    mock_user.create_repo.return_value = mock_repo

    with patch.object(tool, "_get_owner", return_value=mock_user):
        result = await tool.create_repo("my-app", private=True)
        assert result == "testorg/my-app"
        mock_user.create_repo.assert_called_once_with(
            name="my-app",
            private=True,
            auto_init=True,
            description="Auto-generated by App Builder Agent",
        )


@pytest.mark.asyncio
async def test_open_pr_returns_url():
    tool = GithubTool()
    mock_pr = MagicMock()
    mock_pr.html_url = "https://github.com/org/repo/pull/1"
    mock_repo = MagicMock()
    mock_repo.create_pull.return_value = mock_pr

    with patch.object(tool._gh, "get_repo", return_value=mock_repo):
        url = await tool.open_pull_request("org/repo", "Initial Build", "feature/x")
        assert url == "https://github.com/org/repo/pull/1"
