# app/tools/github_tool.py
import logging
import asyncio
from typing import List, Dict
from github import Github, GithubException, Auth, InputGitTreeElement
from app.core.config import settings

logger = logging.getLogger(__name__)

class GithubTool:
    """
    Wraps PyGithub for repo creation, file push, and PR opening.
    Fixed: 
    1. Uses AuthenticatedUser for create_repo.
    2. Uses InputGitTreeElement for pushing multiple files.
    """

    def __init__(self):
        # Your token MUST have 'repo' scope enabled in GitHub Developer Settings
        auth = Auth.Token(settings.github_token)
        self._gh = Github(auth=auth)
        self._org = settings.github_default_org or None

    def _get_owner(self):
        """
        Returns an Organization or AuthenticatedUser object.
        """
        if self._org:
            try:
                return self._gh.get_organization(self._org)
            except GithubException as e:
                logger.warning(f"Org '{self._org}' not accessible: {e}. Falling back to User.")
        
        # get_user() with no args returns the AuthenticatedUser required for create_repo
        return self._gh.get_user()

    async def create_repo(self, name: str, private: bool = True) -> str:
        """
        Creates a new GitHub repository. Returns full_name.
        """
        loop = asyncio.get_event_loop()

        def _create():
            owner = self._get_owner()
            try:
                # Check if repo already exists to prevent 422 errors
                try:
                    existing = owner.get_repo(name)
                    logger.info(f"Repo {name} exists. Using existing.")
                    return existing.full_name
                except GithubException:
                    pass

                repo = owner.create_repo(
                    name=name,
                    private=private,
                    auto_init=True,
                    description="Auto-generated by App Builder Agent",
                )
                logger.info(f"Created repo: {repo.full_name}")
                return repo.full_name
            except Exception as e:
                logger.error(f"Error in create_repo: {e}")
                raise

        return await loop.run_in_executor(None, _create)

    async def push_files(
        self,
        repo_full_name: str,
        branch: str,
        files: List[Dict],
        commit_message: str = "feat: initial build by App Builder Agent",
    ) -> str:
        """
        Atomic multi-file push using the Git Trees API.
        """
        loop = asyncio.get_event_loop()

        def _push():
            repo = self._gh.get_repo(repo_full_name)
            
            # 1. Get base commit from main
            try:
                main_branch = repo.get_branch("main")
                base_sha = main_branch.commit.sha
            except GithubException:
                # Wait for GitHub to finish initializing the repo if auto_init=True was just called
                import time
                time.sleep(3) 
                main_branch = repo.get_branch("main")
                base_sha = main_branch.commit.sha

            # 2. Create the branch ref if it doesn't exist
            try:
                repo.create_git_ref(f"refs/heads/{branch}", base_sha)
            except GithubException as e:
                if "already exists" not in str(e):
                    raise

            # 3. Build tree elements using InputGitTreeElement (FIXES ASSERTION ERROR)
            tree_elements = []
            for f in files:
                path = f.get("path")
                content = f.get("content")
                if not path or content is None:
                    continue
                
                element = InputGitTreeElement(
                    path=path,
                    mode="100644",
                    type="blob",
                    content=content
                )
                tree_elements.append(element)

            if not tree_elements:
                return base_sha

            # 4. Create Git Tree and Commit
            base_tree = repo.get_git_tree(base_sha)
            new_tree = repo.create_git_tree(tree_elements, base_tree)
            parent = repo.get_git_commit(base_sha)
            commit = repo.create_git_commit(commit_message, new_tree, [parent])

            # 5. Update branch pointer
            ref = repo.get_git_ref(f"heads/{branch}")
            ref.edit(commit.sha)
            return commit.sha

        return await loop.run_in_executor(None, _push)

    async def open_pull_request(
        self,
        repo_full_name: str,
        title: str,
        head: str,
        base: str = "main",
    ) -> str:
        """Opens a PR and returns the URL."""
        loop = asyncio.get_event_loop()

        def _pr():
            repo = self._gh.get_repo(repo_full_name)
            pr = repo.create_pull(
                title=title,
                body="PR generated by App Builder Agent",
                head=head,
                base=base,
            )
            return pr.html_url

        return await loop.run_in_executor(None, _pr)

# Singleton instance
github_tool = GithubTool()